CREATE TABLE IF NOT EXISTS `preview_cache_task` (
  `id` int NOT NULL AUTO_INCREMENT,
  `task_no` varchar(50) NOT NULL COMMENT '任务编号',
  `trigger_type` varchar(20) NOT NULL DEFAULT 'manual' COMMENT '触发类型：manual/auto',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '任务状态',
  `total_courses` int NOT NULL DEFAULT 0 COMMENT '课程总数',
  `processed_courses` int NOT NULL DEFAULT 0 COMMENT '已处理课程数',
  `current_course_id` int NULL DEFAULT NULL COMMENT '当前处理课程ID',
  `current_course_name` varchar(255) NULL DEFAULT NULL COMMENT '当前处理课程名称',
  `current_page` int NOT NULL DEFAULT 0 COMMENT '当前课程页码',
  `total_pages` int NOT NULL DEFAULT 0 COMMENT '总页数',
  `processed_pages` int NOT NULL DEFAULT 0 COMMENT '已处理页数',
  `generated_pages` int NOT NULL DEFAULT 0 COMMENT '新生成页数',
  `skipped_pages` int NOT NULL DEFAULT 0 COMMENT '已存在跳过页数',
  `failed_pages` int NOT NULL DEFAULT 0 COMMENT '失败页数',
  `message` text NULL COMMENT '任务消息或错误信息',
  `started_at` datetime NULL DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime NULL DEFAULT NULL COMMENT '完成时间',
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_preview_cache_task_no` (`task_no`),
  KEY `idx_preview_cache_task_status_update_time` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程文件图片缓存生成任务记录';
